source_identifier: CVE-2016-2512
title: Malicious redirect and possible XSS attack via user-supplied redirect URLs
  containing basic auth
description: "Django relies on user input in some cases (e.g. `django.contrib.auth.views.login()`
  and i18n) to redirect the user to an \"on success\" URL. The security check for
  these redirects (namely `django.utils.http.is_safe_url()`) considered some URLs
  with basic authentication credentials \"safe\" when they shouldn't be.\r\n\r\nFor
  example, a URL like `http://mysite.example.com\\@attacker.com` would be considered
  safe if the request's host is `http://mysite.example.com`, but redirecting to this
  URL sends the user to `attacker.com`.\r\n\r\nAlso, if a developer relies on `is_safe_url()`
  to provide safe redirect targets and puts such a URL into a link, they could suffer
  from an XSS attack."
date: "2016-03-01"
affected_range: '>=1.8.0a,<1.8.10||>=1.9.0a,<1.9.3'
fixed_versions:
- 1.8.10
- 1.9.3
affected_versions: 'All versions starting from 1.8.0a before 1.8.10, all versions
  starting from 1.9.0a before 1.9.3'
solution: Upgrade to latest or apply patches. See provided link.
credit: Mark Striemer
urls:
- https://www.djangoproject.com/weblog/2016/mar/01/security-releases/
uuid: c7e6d948-6be8-42f0-880e-c25e02ef86ec
package_slug: pypi/Django
