---
identifier: "CVE-2021-29533"
package_slug: "pypi/tensorflow"
title: "Improper Check for Unusual or Exceptional Conditions"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can trigger a denial of service via a `CHECK` failure by passing an
  empty image to `tf.raw_ops.DrawBoundingBoxes`. This is because the implementation(https://github.com/tensorflow/tensorflow/blob/ea34a18dc3f5c8d80a40ccca1404f343b5d55f91/tensorflow/core/kernels/image/draw_bounding_box_op.cc#L148-L165)
  uses `CHECK_*` assertions instead of `OP_REQUIRES` to validate user controlled inputs.
  Whereas `OP_REQUIRES` allows returning an error condition back to the user, the
  `CHECK_*` macros result in a crash if the condition is false, similar to `assert`.
  In this case, `height` is 0 from the `images` input. This results in `max_box_row_clamp`
  being negative and the assertion being falsified, followed by aborting program execution.
  The fix will be included in TensorFlow We will also cherrypick this commit on TensorFlow,
  TensorFlow, TensorFlow and TensorFlow, as these are also affected and still in supported
  range."
date: "2021-05-17"
pubdate: "2021-05-14"
affected_range: "<=2.1.4||>=2.2.0,<=2.2.3||>=2.3.0,<=2.3.3||>=2.4.0,<=2.4.2"
fixed_versions:
- "2.5.0"
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: "All versions after 2.1.4 before 2.2.0, all versions after 2.2.3 before
  2.3.0, all versions after 2.3.3 before 2.4.0, all versions after 2.4.2"
solution: "Upgrade to version 2.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29533"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "166e7cdd-9c5f-4dce-b49a-83378d6b10c6"
