---
identifier: "CVE-2021-37687"
package_slug: "pypi/tensorflow"
title: "Out-of-bounds Read"
description: "TensorFlow is an end-to-end open source platform for machine learning.Hence,
  an attacker can read arbitrary data from the heap by carefully crafting a model
  with negative values in `indices`. Similar issue exists in [`Gather` implementation](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/lite/kernels/gather.cc).
  We have patched the issue in GitHub commits bb6a0383ed553c286f87ca88c207f6774d5c4a8f
  and eb921122119a6b6e470ee98b89e65d721663179d. The fix will be included in TensorFlow
  We will also cherrypick this commit on TensorFlow, TensorFlow, and TensorFlow, as
  these are also affected and still in supported range."
date: "2021-08-18"
pubdate: "2021-08-12"
affected_range: ">=2.3.0,<2.3.4||>=2.4.0,<2.4.3||>=2.5.0,<=2.6.0"
fixed_versions:
- "2.3.4"
- "2.4.3"
affected_versions: "All versions starting from 2.3.0 before 2.3.4, all versions starting
  from 2.4.0 before 2.4.3, all versions starting from 2.5.0 up to 2.6.0"
not_impacted: "All versions before 2.3.0, all versions starting from 2.3.4 before
  2.4.0, all versions starting from 2.4.3 before 2.5.0, all versions after 2.6.0"
solution: "Upgrade to versions 2.3.4, 2.4.3 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-37687"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:N/A:N"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
uuid: "4a7ed13c-3c81-4ac7-a62e-d18f44838c33"
