---
identifier: "CVE-2021-29614"
package_slug: "pypi/tensorflow"
title: "Improper Initialization"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  The implementation of `tf.io.decode_raw` produces incorrect results and crashes
  the Python interpreter when combining `fixed_length` and wider datatypes. The implementation
  of the padded version(https://github.com/tensorflow/tensorflow/blob/1d8903e5b167ed0432077a3db6e462daf781d1fe/tensorflow/core/kernels/decode_padded_raw_op.cc)
  is buggy due to a confusion about pointer arithmetic rules. First, the code computes(https://github.com/tensorflow/tensorflow/blob/1d8903e5b167ed0432077a3db6e462daf781d1fe/tensorflow/core/kernels/decode_padded_raw_op.cc#L61)
  the width of each output element by dividing the `fixed_length` value to the size
  of the type argument. The `fixed_length` argument is also used to determine the
  size needed for the output tensor(https://github.com/tensorflow/tensorflow/blob/1d8903e5b167ed0432077a3db6e462daf781d1fe/tensorflow/core/kernels/decode_padded_raw_op.cc#L63-L79).
  This is followed by reencoding code(https://github.com/tensorflow/tensorflow/blob/1d8903e5b167ed0432077a3db6e462daf781d1fe/tensorflow/core/kernels/decode_padded_raw_op.cc#L85-L94).
  The erroneous code is the last line above: it is moving the `out_data` pointer by
  `fixed_length * sizeof(T)` bytes whereas it only copied at most `fixed_length` bytes
  from the input. This results in parts of the input not being decoded into the output.
  Furthermore, because the pointer advance is far wider than desired, this quickly
  leads to writing to outside the bounds of the backing data. This OOB write leads
  to interpreter crash in the reproducer mentioned here, but more severe attacks can
  be mounted too, given that this gadget allows writing to periodically placed locations
  in memory. The fix will be included in TensorFlow We will also cherrypick this commit
  on TensorFlow, TensorFlow, TensorFlow and TensorFlow, as these are also affected
  and still in supported range."
date: "2021-05-20"
pubdate: "2021-05-14"
affected_range: "<2.1.4||>=2.2.0,<2.2.3||>=2.3.0,<2.3.3||>=2.4.0,<2.4.2"
fixed_versions:
- "2.5.0"
affected_versions: "All versions before 2.1.4, all versions starting from 2.2.0 before
  2.2.3, all versions starting from 2.3.0 before 2.3.3, all versions starting from
  2.4.0 before 2.4.2"
not_impacted: "All versions starting from 2.1.4 before 2.2.0, all versions starting
  from 2.2.3 before 2.3.0, all versions starting from 2.3.3 before 2.4.0, all versions
  starting from 2.4.2"
solution: "Upgrade to version 2.5.0 or above."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29614"
cvss_v2: "AV:L/AC:L/Au:N/C:P/I:P/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
uuid: "5bf7db12-272a-491b-92e2-a43a4f0edc09"
