---
identifier: "CVE-2021-29543"
package_slug: "maven/org.tensorflow/parentpom"
title: "Reachable Assertion"
description: "TensorFlow is an end-to-end open source platform for machine learning.
  An attacker can trigger a denial of service via a `CHECK`-fail in `tf.raw_ops.CTCGreedyDecoder`.
  This is because the implementation(https://github.com/tensorflow/tensorflow/blob/1615440b17b364b875eb06f43d087381f1460a65/tensorflow/core/kernels/ctc_decoder_ops.cc#L37-L50)
  has a `CHECK_LT` inserted to validate some invariants. When this condition is false,
  the program aborts, instead of returning a valid error to the user. This abnormal
  termination can be weaponized in denial of service attacks. The fix will be included
  in TensorFlow We will also cherrypick this commit on TensorFlow, TensorFlow, TensorFlow
  and TensorFlow, as these are also affected and still in supported range."
date: "2021-05-18"
pubdate: "2021-05-14"
affected_range: "(,2.1.4],[2.2.0,2.2.3],[2.3.0,2.3.3],[2.4.0,2.4.2]"
fixed_versions: []
affected_versions: "All versions up to 2.1.4, all versions starting from 2.2.0 up
  to 2.2.3, all versions starting from 2.3.0 up to 2.3.3, all versions starting from
  2.4.0 up to 2.4.2"
not_impacted: ""
solution: "Unfortunately, there is no solution available yet."
urls:
- "https://nvd.nist.gov/vuln/detail/CVE-2021-29543"
cvss_v2: "AV:L/AC:L/Au:N/C:N/I:N/A:P"
cvss_v3: "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
uuid: "08bdd213-4ef1-46e1-aef9-20e3db009720"
